"""initial

Revision ID: 165f8f67bc70
Revises: 
Create Date: 2026-05-08 14:26:34.155300
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from pgvector.sqlalchemy import Vector

revision: str = '165f8f67bc70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('parse_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('depth_level', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mastery_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_cycle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prompt_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('domain_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('answer_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('common_pitfalls', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tag_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('related_question_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', Vector(512), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('study_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('review_result', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_records')
    # Note: not dropping vector extension to avoid CASCADE issues
    op.drop_table('question_tags')
    op.drop_table('question_knowledge_nodes')
    op.drop_table('question_embeddings')
    op.drop_table('chat_histories')
    op.drop_table('tags')
    op.drop_table('questions')
    op.drop_table('prompt_versions')
    op.drop_table('learning_profiles')
    op.drop_table('knowledge_nodes')
    op.drop_table('files')
    # ### end Alembic commands ###
