"""add_exam_sessions_and_exam_answers_tables

Revision ID: 8675172568af
Revises: add_user_id_to_resumes_questions
Create Date: 2026-05-12 14:08:43.639823
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString
from sqlalchemy.dialects import postgresql

revision: str = '8675172568af'
down_revision: Union[str, None] = 'add_user_id_to_resumes_questions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', AutoString(length=255), nullable=True),
    sa.Column('title', AutoString(length=200), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('difficulty_filter', AutoString(length=50), nullable=True),
    sa.Column('source_filter', AutoString(length=50), nullable=True),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('user_answer', AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', AutoString(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.drop_table('exam_answers')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
